/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.codejava.e_health.E_health;

/**
 *
 * @author User
 */
public class insert extends javax.swing.JFrame {

    /**
     * Creates new form insert
     */
    public insert() {
        initComponents();
                    jLabel6.setVisible(false);
                    jLabel7.setVisible(false);
                    jLabel8.setVisible(false);
                    jLabel9.setVisible(false);
                    jLabel10.setVisible(false);
                    jLabel11.setVisible(false);
                    jLabel12.setVisible(false);
                    jLabel13.setVisible(false);
                    jLabel14.setVisible(false);
                    jLabel15.setVisible(false);
                    jLabel16.setVisible(false);
                    jLabel17.setVisible(false);
                    jLabel18.setVisible(false);
                    jLabel19.setVisible(false);

                    jTextField2.setVisible(false);
                    jTextField3.setVisible(false);
                    jTextField4.setVisible(false);
                    jComboBox2.setVisible(false);
                    jTextField6.setVisible(false);
                    jTextField7.setVisible(false);
                    jTextField8.setVisible(false);
                    jTextField9.setVisible(false);
                    jComboBox5.setVisible(false);
                    jComboBox3.setVisible(false);
                    jTextField12.setVisible(false);
                    jComboBox4.setVisible(false);
                    jTextField14.setVisible(false);
                    jTextField15.setVisible(false);
                    
                    jButton3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 150, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 150, -1));

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 150, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Username");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setText("Insert Window");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Teacher", "Doctor", "Nurse", "Student" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 140, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 140, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Input Username:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("User Type:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Blood Group");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 330, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Student_ID");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 370, -1, -1));

        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, 150, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Designation");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 410, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Contact No");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, -1, -1));

        jTextField14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 450, 150, -1));

        jTextField15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, 150, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("District");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 490, -1, -1));

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 490, 150, -1));

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 150, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Gender");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Department");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Age");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Height");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, -1, -1));

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, 150, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Weight");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 570, -1, 20));

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 570, 150, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Donar");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 610, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 610, 130, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insert big.png"))); // NOI18N
        jButton3.setText("Insert");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 570, 150, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 150, -1));

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A(+)", "A(-)", "B(+)", "B(-)", "AB(+)", "AB(-)", "O(+)", "O(-)" }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 330, 150, -1));

        jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "lecturer", "Assistant Professor", "Associate Professor", "Professor" }));
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 410, 150, -1));

        jComboBox5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO" }));
        getContentPane().add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 610, 150, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back show big.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        // jTextField3.setVisible(false);

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {     
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField6.setText("");
                    jTextField7.setText("");
                    jTextField8.setText("");
                    jTextField9.setText("");
                    ////jComboBox5.setText("");
                    jTextField12.setText("");
                    jTextField14.setText("");
                    jTextField15.setText("");

            //declare the parameter of connection
            String url = "jdbc:mysql://localhost:3307/bsmrstu_community";
            String user = "root";
            String password = "juwelmallick";
            Class.forName("com.mysql.cj.jdbc.Driver");

            //for a new connection with database
            Connection c  = DriverManager.getConnection(url,user, password);
            //Statement statement = c.createStatement();
            //String query1 = "SELECT * FROM bsmrstu_community.password";//WHERE username=? and password=? and usertype=?;
            Statement s1 = c.createStatement();

            if(jComboBox1.getSelectedIndex()==0)
            {

                String q1 = "SELECT * FROM bsmrstu_community.admin;";
                ResultSet r1= s1.executeQuery(q1);

                //String u1 = jTextField1.getText();

                int n=0;
                while(r1.next())
                {
                    String name, us, pas;

                    us = r1.getString("username");

                    if(jTextField1.getText().equals(us))
                    {
                         
                        n=1;
                        
                    jLabel6.setVisible(false);
                    jLabel7.setVisible(false);
                    jLabel8.setVisible(false);
                    jLabel9.setVisible(false);
                    jLabel10.setVisible(false);
                    jLabel11.setVisible(false);
                    jLabel12.setVisible(false);
                    jLabel13.setVisible(false);
                    jLabel14.setVisible(false);
                    jLabel15.setVisible(false);
                    jLabel16.setVisible(false);
                    jLabel17.setVisible(false);
                    jLabel18.setVisible(false);
                    jLabel19.setVisible(false);

                    jTextField2.setVisible(false);
                    jTextField3.setVisible(false);
                    jTextField4.setVisible(false);
                    jComboBox2.setVisible(false);
                    jTextField6.setVisible(false);
                    jTextField7.setVisible(false);
                    jTextField8.setVisible(false);
                    jTextField9.setVisible(false);
                    jComboBox5.setVisible(false);
                    jComboBox3.setVisible(false);
                    jTextField12.setVisible(false);
                    jComboBox4.setVisible(false);
                    jTextField14.setVisible(false);
                    jTextField15.setVisible(false);
                    
                    jButton3.setVisible(false);
                        JOptionPane.showMessageDialog(this, "Username already exist choose different");
                        
                        
                        break;
                    }
                } if(n==0)
                {
                    //jTextField2.setText("hello");
                    
                    
                    
                    jLabel6.setVisible(false);
                    jLabel7.setVisible(true);
                    jLabel8.setVisible(true);
                    jLabel9.setVisible(false);
                    jLabel10.setVisible(false);
                    jLabel11.setVisible(false);
                    jLabel12.setVisible(false);
                    jLabel13.setVisible(false);
                    jLabel14.setVisible(false);
                    jLabel15.setVisible(false);
                    jLabel16.setVisible(false);
                    jLabel17.setVisible(false);
                    jLabel18.setVisible(false);
                    jLabel19.setVisible(false);

                    jTextField2.setVisible(false);
                    jTextField3.setVisible(true);
                    jTextField4.setVisible(true);
                    jComboBox2.setVisible(false);
                    jTextField6.setVisible(false);
                    jTextField7.setVisible(false);
                    jTextField8.setVisible(false);
                    jTextField9.setVisible(false);
                    jComboBox5.setVisible(false);
                    jComboBox3.setVisible(false);
                    jTextField12.setVisible(false);
                    jComboBox4.setVisible(false);
                    jTextField14.setVisible(false);
                    jTextField15.setVisible(false);
                    
                    jButton3.setVisible(true);
                    
//                    String us = r1.getString("username");
//                    String name = r1.getString("name");
//                    String pas = r1.getString("password");
                    
                }
            }

            //Teacher
            else if(jComboBox1.getSelectedIndex()==1)
            {
                String q1 = "SELECT * FROM bsmrstu_community.teacher;";
                ResultSet r1= s1.executeQuery(q1);

                //String u1 = jTextField1.getText();

                int n=0;
                while(r1.next())
                {
                    String name, us, pas;

                    us = r1.getString("username");

                    if(jTextField1.getText().equals(us))
                    {
                         
                        n=1;
                        
                    jLabel6.setVisible(false);
                    jLabel7.setVisible(false);
                    jLabel8.setVisible(false);
                    jLabel9.setVisible(false);
                    jLabel10.setVisible(false);
                    jLabel11.setVisible(false);
                    jLabel12.setVisible(false);
                    jLabel13.setVisible(false);
                    jLabel14.setVisible(false);
                    jLabel15.setVisible(false);
                    jLabel16.setVisible(false);
                    jLabel17.setVisible(false);
                    jLabel18.setVisible(false);
                    jLabel19.setVisible(false);

                    jTextField2.setVisible(false);
                    jTextField3.setVisible(false);
                    jTextField4.setVisible(false);
                    jComboBox2.setVisible(false);
                    jTextField6.setVisible(false);
                    jTextField7.setVisible(false);
                    jTextField8.setVisible(false);
                    jTextField9.setVisible(false);
                    jComboBox5.setVisible(false);
                    jComboBox3.setVisible(false);
                    jTextField12.setVisible(false);
                    jComboBox4.setVisible(false);
                    jTextField14.setVisible(false);
                    jTextField15.setVisible(false);
                    
                    jButton3.setVisible(false);
                        JOptionPane.showMessageDialog(this, "Username already exist choose different");
                        
                        
                        break;
                    }
                } if(n==0)
                {
                    //jTextField2.setText("hello");
                    
                    
                    
                    jLabel6.setVisible(false);
                    jLabel7.setVisible(true);
                    jLabel8.setVisible(true);
                    jLabel9.setVisible(true);
                    jLabel10.setVisible(true);
                    jLabel11.setVisible(true);
                    jLabel12.setVisible(true);
                    jLabel13.setVisible(true);
                    jLabel14.setVisible(true);
                    jLabel15.setVisible(true);
                    jLabel16.setVisible(false);//
                    jLabel17.setVisible(true);
                    jLabel18.setVisible(true);
                    jLabel19.setVisible(true);

                    jTextField2.setVisible(false);
                    jTextField3.setVisible(true);
                    jTextField4.setVisible(true);
                    jComboBox2.setVisible(true);
                    jTextField6.setVisible(true);
                    jTextField7.setVisible(true);
                    jTextField8.setVisible(true);
                    jTextField9.setVisible(true);
                    jComboBox5.setVisible(true);
                    jComboBox3.setVisible(true);
                    jTextField12.setVisible(false);//
                    jComboBox4.setVisible(true);
                    jTextField14.setVisible(true);
                    jTextField15.setVisible(true);
                    
                    jButton3.setVisible(true);
                    
//                    String us = r1.getString("username");
//                    String name = r1.getString("name");
//                    String pas = r1.getString("password");
                    
                }
            }
            else if(jComboBox1.getSelectedIndex()==2)
            {String q1 = "SELECT * FROM bsmrstu_community.doctor;";
                ResultSet r1= s1.executeQuery(q1);

                //String u1 = jTextField1.getText();

                int n=0;
                while(r1.next())
                {
                    String name, us, pas;

                    us = r1.getString("username");

                    if(jTextField1.getText().equals(us))
                    {
                         
                        n=1;
                        
                    jLabel6.setVisible(false);
                    jLabel7.setVisible(false);
                    jLabel8.setVisible(false);
                    jLabel9.setVisible(false);
                    jLabel10.setVisible(false);
                    jLabel11.setVisible(false);
                    jLabel12.setVisible(false);
                    jLabel13.setVisible(false);
                    jLabel14.setVisible(false);
                    jLabel15.setVisible(false);
                    jLabel16.setVisible(false);
                    jLabel17.setVisible(false);
                    jLabel18.setVisible(false);
                    jLabel19.setVisible(false);

                    jTextField2.setVisible(false);
                    jTextField3.setVisible(false);
                    jTextField4.setVisible(false);
                    jComboBox2.setVisible(false);
                    jTextField6.setVisible(false);
                    jTextField7.setVisible(false);
                    jTextField8.setVisible(false);
                    jTextField9.setVisible(false);
                    jComboBox5.setVisible(false);
                    jComboBox3.setVisible(false);
                    jTextField12.setVisible(false);
                    jComboBox4.setVisible(false);
                    jTextField14.setVisible(false);
                    jTextField15.setVisible(false);
                    
                    jButton3.setVisible(false);
                        JOptionPane.showMessageDialog(this, "Username already exist choose different");
                        
                        
                        break;
                    }
                } if(n==0)
                {
                    //jTextField2.setText("hello");
                    
                    
                    
                    jLabel6.setVisible(false);
                    jLabel7.setVisible(true);
                    jLabel8.setVisible(true);
                    jLabel9.setVisible(true);
                    jLabel10.setVisible(false);
                    jLabel11.setVisible(false);
                    jLabel12.setVisible(false);
                    jLabel13.setVisible(false);
                    jLabel14.setVisible(false);
                    jLabel15.setVisible(false);
                    jLabel16.setVisible(false);
                    jLabel17.setVisible(false);
                    jLabel18.setVisible(false);
                    jLabel19.setVisible(false);

                    jTextField2.setVisible(false);
                    jTextField3.setVisible(true);
                    jTextField4.setVisible(true);
                    jComboBox2.setVisible(true);
                    jTextField6.setVisible(false);
                    jTextField7.setVisible(false);
                    jTextField8.setVisible(false);
                    jTextField9.setVisible(false);
                    jComboBox5.setVisible(false);
                    jComboBox3.setVisible(false);
                    jTextField12.setVisible(false);
                    jComboBox4.setVisible(false);
                    jTextField14.setVisible(false);
                    jTextField15.setVisible(false);
                    
                    jButton3.setVisible(true);
                    
//                    String us = r1.getString("username");
//                    String name = r1.getString("name");
//                    String pas = r1.getString("password");
                    
                }
            }
            else if(jComboBox1.getSelectedIndex()==3)
            {String q1 = "SELECT * FROM bsmrstu_community.nurse;";
                ResultSet r1= s1.executeQuery(q1);

                //String u1 = jTextField1.getText();

                int n=0;
                while(r1.next())
                {
                    String name, us, pas;

                    us = r1.getString("username");

                    if(jTextField1.getText().equals(us))
                    {
                         
                        n=1;
                        
                    jLabel6.setVisible(false);
                    jLabel7.setVisible(false);
                    jLabel8.setVisible(false);
                    jLabel9.setVisible(false);
                    jLabel10.setVisible(false);
                    jLabel11.setVisible(false);
                    jLabel12.setVisible(false);
                    jLabel13.setVisible(false);
                    jLabel14.setVisible(false);
                    jLabel15.setVisible(false);
                    jLabel16.setVisible(false);
                    jLabel17.setVisible(false);
                    jLabel18.setVisible(false);
                    jLabel19.setVisible(false);

                    jTextField2.setVisible(false);
                    jTextField3.setVisible(false);
                    jTextField4.setVisible(false);
                    jComboBox2.setVisible(false);
                    jTextField6.setVisible(false);
                    jTextField7.setVisible(false);
                    jTextField8.setVisible(false);
                    jTextField9.setVisible(false);
                    jComboBox5.setVisible(false);
                    jComboBox3.setVisible(false);
                    jTextField12.setVisible(false);
                    jComboBox4.setVisible(false);
                    jTextField14.setVisible(false);
                    jTextField15.setVisible(false);
                    
                    jButton3.setVisible(false);
                        JOptionPane.showMessageDialog(this, "Username already exist choose different");
                        
                        
                        break;
                    }
                } if(n==0)
                {
                    //jTextField2.setText("hello");
                    
                    
                    
                    jLabel6.setVisible(false);
                    jLabel7.setVisible(true);
                    jLabel8.setVisible(true);
                    jLabel9.setVisible(false);
                    jLabel10.setVisible(false);
                    jLabel11.setVisible(false);
                    jLabel12.setVisible(false);
                    jLabel13.setVisible(false);
                    jLabel14.setVisible(false);
                    jLabel15.setVisible(false);
                    jLabel16.setVisible(false);
                    jLabel17.setVisible(false);
                    jLabel18.setVisible(false);
                    jLabel19.setVisible(false);

                    jTextField2.setVisible(false);
                    jTextField3.setVisible(true);
                    jTextField4.setVisible(true);
                    jComboBox2.setVisible(false);
                    jTextField6.setVisible(false);
                    jTextField7.setVisible(false);
                    jTextField8.setVisible(false);
                    jTextField9.setVisible(false);
                    jComboBox5.setVisible(false);
                    jComboBox3.setVisible(false);
                    jTextField12.setVisible(false);
                    jComboBox4.setVisible(false);
                    jTextField14.setVisible(false);
                    jTextField15.setVisible(false);
                    
                    jButton3.setVisible(true);
                    
//                    String us = r1.getString("username");
//                    String name = r1.getString("name");
//                    String pas = r1.getString("password");
                    
                }
            }
            else if(jComboBox1.getSelectedIndex()==4)
            {String q1 = "SELECT * FROM bsmrstu_community.student;";
                ResultSet r1= s1.executeQuery(q1);

                //String u1 = jTextField1.getText();

                int n=0;
                while(r1.next())
                {
                    String name, us, pas;

                    us = r1.getString("username");

                    if(jTextField1.getText().equals(us))
                    {
                         
                        n=1;
                        
                    jLabel6.setVisible(false);
                    jLabel7.setVisible(false);
                    jLabel8.setVisible(false);
                    jLabel9.setVisible(false);
                    jLabel10.setVisible(false);
                    jLabel11.setVisible(false);
                    jLabel12.setVisible(false);
                    jLabel13.setVisible(false);
                    jLabel14.setVisible(false);
                    jLabel15.setVisible(false);
                    jLabel16.setVisible(false);
                    jLabel17.setVisible(false);
                    jLabel18.setVisible(false);
                    jLabel19.setVisible(false);

                    jTextField2.setVisible(false);
                    jTextField3.setVisible(false);
                    jTextField4.setVisible(false);
                    jComboBox2.setVisible(false);
                    jTextField6.setVisible(false);
                    jTextField7.setVisible(false);
                    jTextField8.setVisible(false);
                    jTextField9.setVisible(false);
                    jComboBox5.setVisible(false);
                    jComboBox3.setVisible(false);
                    jTextField12.setVisible(false);
                    jComboBox4.setVisible(false);
                    jTextField14.setVisible(false);
                    jTextField15.setVisible(false);
                    
                    jButton3.setVisible(false);
                        JOptionPane.showMessageDialog(this, "Username already exist choose different");
                        
                        
                        break;
                    }
                } if(n==0)
                {
                    //jTextField2.setText("hello");
                    
                    
                    
                    jLabel6.setVisible(false);
                    jLabel7.setVisible(true);
                    jLabel8.setVisible(true);
                    jLabel9.setVisible(true);
                    jLabel10.setVisible(true);
                    jLabel11.setVisible(true);
                    jLabel12.setVisible(true);
                    jLabel13.setVisible(true);
                    jLabel14.setVisible(true);
                    jLabel15.setVisible(true);
                    jLabel16.setVisible(true);
                    jLabel17.setVisible(false);
                    jLabel18.setVisible(true);
                    jLabel19.setVisible(true);

                    jTextField2.setVisible(false);
                    jTextField3.setVisible(true);
                    jTextField4.setVisible(true);
                    jComboBox2.setVisible(true);
                    jTextField6.setVisible(true);
                    jTextField7.setVisible(true);
                    jTextField8.setVisible(true);
                    jTextField9.setVisible(true);
                    jComboBox5.setVisible(true);
                    jComboBox3.setVisible(true);
                    jTextField12.setVisible(true);
                    jComboBox4.setVisible(false);
                    jTextField14.setVisible(true);
                    jTextField15.setVisible(true);
                    
                    jButton3.setVisible(true);
                    
//                    String us = r1.getString("username");
//                    String name = r1.getString("name");
//                    String pas = r1.getString("password");
                    
                }
            }

        }catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(E_health.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
        jTextField3.setText("null");
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new show().setVisible(false);
        new admin().setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {

            //declare the parameter of connection
            String url = "jdbc:mysql://localhost:3307/bsmrstu_community";
            String user = "root";
            String password = "juwelmallick";
            Class.forName("com.mysql.cj.jdbc.Driver");

            //for a new connection with database
            Connection c  = DriverManager.getConnection(url,user, password);
            //Statement statement = c.createStatement();
            //String query1 = "SELECT * FROM bsmrstu_community.password";//WHERE username=? and password=? and usertype=?;
            Statement s1 = c.createStatement();

            if(jComboBox1.getSelectedIndex()==0)
            {

                String q2 = "SELECT * FROM bsmrstu_community.admin;";
                ResultSet r2= s1.executeQuery(q2);
         
                    String us = jTextField1.getText();
                    String name = jTextField3.getText();
                    String pas = jTextField4.getText();
//                    if(jComboBox2.getSelectedIndex() == 0)
//                    {
//                        String des = "Male";
//                    }
//                    else if(jComboBox2.getSelectedIndex() == 1)
//                    {
//                        String des = "Female";
//                    }
//                    else
//                    {
//                        String des = "Others";
//                    }
//                     String dept = jTextField6.getText();
//                    int age = Integer.parseInt(jTextField7.getText());
//                    int height = Integer.parseInt(jTextField8.getText());
//                    int weight = Integer.parseInt(jTextField9.getText());
//                    String donor = jComboBox5.getText();
//                    if(jComboBox3.getSelectedIndex() == 0)
//                    {
//                        String blood = "A+";
//                    }
//                    else if(jComboBox3.getSelectedIndex() == 1)
//                    {
//                        String blood = "A-";
//                    }
//                    else if(jComboBox3.getSelectedIndex() == 2)
//                    {
//                        String blood = "B+";
//                    }
//                    else if(jComboBox3.getSelectedIndex() == 3)
//                    {
//                        String blood = "B-";
//                    }
//                    else if(jComboBox3.getSelectedIndex() == 4)
//                    {
//                        String blood = "AB+";
//                    }
//                    else if(jComboBox3.getSelectedIndex() == 5)
//                    {
//                        String blood = "AB-";
//                    }
//                    else if(jComboBox3.getSelectedIndex() == 7)
//                    {
//                        String blood = "O+";
//                    }
//                    else 
//                    {
//                        String blood = "O-";
//                    }
//                    String sid = jTextField12.getText();
//                    String des = jComboBox4.getText();
//                    String con = jTextField14.getText();
//                    String dis = jTextField15.getText();
//                    
                    
                    
                    
                    //JOptionPane.showMessageDialog(this, us + " " +name + " " + pas);

                String q3 = "INSERT INTO `bsmrstu_community`.`admin` (`name`, `username`, `password`) VALUES ('"+name+"', '"+us+"', '"+pas+"')";
                s1.executeUpdate(q3);
                   
                    
                    
                   JOptionPane.showMessageDialog(this,"Successfully inserted data"); 
                   jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField6.setText("");
                    jTextField7.setText("");
                    jTextField8.setText("");
                    jTextField9.setText("");
                    //jComboBox5.setText("");
                    jTextField12.setText("");
                    jTextField14.setText("");
                    jTextField15.setText("");
                    
                    
                    jLabel7.setVisible(false);
                    jLabel8.setVisible(false);
                    jLabel9.setVisible(false);
                    jLabel10.setVisible(false);
                    jLabel11.setVisible(false);
                    jLabel12.setVisible(false);
                    jLabel13.setVisible(false);
                    jLabel14.setVisible(false);
                    jLabel15.setVisible(false);
                    jLabel16.setVisible(false);
                    jLabel17.setVisible(false);
                    jLabel18.setVisible(false);
                    jLabel19.setVisible(false);

                    jTextField2.setVisible(false);
                    jTextField3.setVisible(false);
                    jTextField4.setVisible(false);
                    jComboBox2.setVisible(false);
                    jTextField6.setVisible(false);
                    jTextField7.setVisible(false);
                    jTextField8.setVisible(false);
                    jTextField9.setVisible(false);
                    jComboBox5.setVisible(false);
                    jComboBox3.setVisible(false);
                    jTextField12.setVisible(false);
                    jComboBox4.setVisible(false);
                    jTextField14.setVisible(false);
                    jTextField15.setVisible(false);
                    
                    jButton3.setVisible(false);
           
            }
            if(jComboBox1.getSelectedIndex()==1)
            {

                String q2 = "SELECT * FROM bsmrstu_community.teacher;";
                ResultSet r2= s1.executeQuery(q2);
         
                    String us = jTextField1.getText();
                    String name = jTextField3.getText();
                    String pas = jTextField4.getText();
                    String gen;
                    if(jComboBox2.getSelectedIndex() == 0)
                    {
                         gen = "Male";
                    }
                    else if(jComboBox2.getSelectedIndex() == 1)
                    {
                         gen = "Female";
                    }
                    else
                    {
                         gen = "Others";
                    }
                     String dept = jTextField6.getText();
                    int age = Integer.parseInt(jTextField7.getText());
                    int height = Integer.parseInt(jTextField8.getText());
                    int weight = Integer.parseInt(jTextField9.getText());
                    String donor;
                    
                    if(jComboBox5.getSelectedIndex() == 0)
                    {
                         donor = "YES";
                    }
                    else 
                    {
                         donor = "NO";
                    }
                    String blood;
                    if(jComboBox3.getSelectedIndex() == 0)
                    {
                         blood = "A+";
                    }
                    else if(jComboBox3.getSelectedIndex() == 1)
                    {
                         blood = "A-";
                    }
                    else if(jComboBox3.getSelectedIndex() == 2)
                    {
                         blood = "B+";
                    }
                    else if(jComboBox3.getSelectedIndex() == 3)
                    {
                         blood = "B-";
                    }
                    else if(jComboBox3.getSelectedIndex() == 4)
                    {
                         blood = "AB+";
                    }
                    else if(jComboBox3.getSelectedIndex() == 5)
                    {
                         blood = "AB-";
                    }
                    else if(jComboBox3.getSelectedIndex() == 7)
                    {
                         blood = "O+";
                    }
                    else 
                    {
                         blood = "O-";
                    }
                    //String sid = jTextField12.getText();
                    String des;
                    if(jComboBox4.getSelectedIndex() == 0)
                    {
                         des = "Lecturer";
                    }
                    else if(jComboBox4.getSelectedIndex() == 1)
                    {
                         des = "Assistant Professor";
                    }
                    else if(jComboBox4.getSelectedIndex() == 2)
                    {
                         des = "Associate Professor";
                    }
                    else
                    {
                         des = "Professor";
                    }
                    
                    String con = jTextField14.getText();
                    String dis = jTextField15.getText();
                    
                    
                    
                    
                    //JOptionPane.showMessageDialog(this, us + " " +name + " " + pas);

                String q3 = "INSERT INTO `bsmrstu_community`.`teacher` (`name`, `username`, `password`,`designation`, `department`, `age`,`height`, `weight`, `blood`,`donar`, `district`, `gender`, `contact`) VALUES ('"+name+"', '"+us+"', '"+pas+"','"+des+"', '"+dept+"', '"+age+"','"+height+"', '"+weight+"','"+blood+"', '"+donor+"', '"+dis+"','"+gen+"', '"+con+"')";
               //                String q3 = "INSERT INTO `bsmrstu_community`.`admin` (`name`, `username`, `password`,`designation`, `department`, `age`,`height`, `weight`, `blood`,`donar`, `district`, `gender`, `contact`) VALUES ('"+name+"', '"+us+"', '"+pas+"','"+des+"', '"+dept+"', '"+age+"','"+height+"', '"+weight+"', '"+blood+"')";

                s1.executeUpdate(q3);
                
                   JOptionPane.showMessageDialog(this,"Successfully inserted data");
                   
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField6.setText("");
                    jTextField7.setText("");
                    jTextField8.setText("");
                    jTextField9.setText("");
                    //jComboBox5.setText("");
                    jTextField12.setText("");
                    jTextField14.setText("");
                    jTextField15.setText("");
                    
                    
                    jLabel7.setVisible(false);
                    jLabel8.setVisible(false);
                    jLabel9.setVisible(false);
                    jLabel10.setVisible(false);
                    jLabel11.setVisible(false);
                    jLabel12.setVisible(false);
                    jLabel13.setVisible(false);
                    jLabel14.setVisible(false);
                    jLabel15.setVisible(false);
                    jLabel16.setVisible(false);
                    jLabel17.setVisible(false);
                    jLabel18.setVisible(false);
                    jLabel19.setVisible(false);

                    jTextField2.setVisible(false);
                    jTextField3.setVisible(false);
                    jTextField4.setVisible(false);
                    jComboBox2.setVisible(false);
                    jTextField6.setVisible(false);
                    jTextField7.setVisible(false);
                    jTextField8.setVisible(false);
                    jTextField9.setVisible(false);
                    jComboBox5.setVisible(false);
                    jComboBox3.setVisible(false);
                    jTextField12.setVisible(false);
                    jComboBox4.setVisible(false);
                    jTextField14.setVisible(false);
                    jTextField15.setVisible(false);
                    
                    jButton3.setVisible(false);
           
            }
            if(jComboBox1.getSelectedIndex()==2)
            {

                String q2 = "SELECT * FROM bsmrstu_community.doctor;";
                ResultSet r2= s1.executeQuery(q2);
         
                    String us = jTextField1.getText();
                    String name = jTextField3.getText();
                    String pas = jTextField4.getText();
                    String gen;
                    if(jComboBox2.getSelectedIndex() == 0)
                    {
                         gen = "Male";
                    }
                    else if(jComboBox2.getSelectedIndex() == 1)
                    {
                         gen = "Female";
                    }
                    else
                    {
                         gen = "Others";
                    }
                    
                    /*
                     String dept = jTextField6.getText();
                    int age = Integer.parseInt(jTextField7.getText());
                    int height = Integer.parseInt(jTextField8.getText());
                    int weight = Integer.parseInt(jTextField9.getText());
                    String donor = jComboBox5.getText();
                    String blood;
                    if(jComboBox3.getSelectedIndex() == 0)
                    {
                         blood = "A+";
                    }
                    else if(jComboBox3.getSelectedIndex() == 1)
                    {
                         blood = "A-";
                    }
                    else if(jComboBox3.getSelectedIndex() == 2)
                    {
                         blood = "B+";
                    }
                    else if(jComboBox3.getSelectedIndex() == 3)
                    {
                         blood = "B-";
                    }
                    else if(jComboBox3.getSelectedIndex() == 4)
                    {
                         blood = "AB+";
                    }
                    else if(jComboBox3.getSelectedIndex() == 5)
                    {
                         blood = "AB-";
                    }
                    else if(jComboBox3.getSelectedIndex() == 7)
                    {
                         blood = "O+";
                    }
                    else 
                    {
                         blood = "O-";
                    }
                    //String sid = jTextField12.getText();
                    String des;
                    if(jComboBox4.getSelectedIndex() == 0)
                    {
                         des = "Lecturer";
                    }
                    else if(jComboBox4.getSelectedIndex() == 1)
                    {
                         des = "Assistant Professor";
                    }
                    else if(jComboBox4.getSelectedIndex() == 2)
                    {
                         des = "Associate Professor";
                    }
                    else
                    {
                         des = "Professor";
                    }
                    
                    String con = jTextField14.getText();
                    String dis = jTextField15.getText();
                    */
                    
                    
                    
                    //JOptionPane.showMessageDialog(this, us + " " +name + " " + pas);

                String q3 = "INSERT INTO `bsmrstu_community`.`doctor` (`name`, `username`, `password`,  `gender`) VALUES ('"+name+"', '"+us+"', '"+pas+"','"+gen+"')";
               //                String q3 = "INSERT INTO `bsmrstu_community`.`admin` (`name`, `username`, `password`,`designation`, `department`, `age`,`height`, `weight`, `blood`,`donar`, `district`, `gender`, `contact`) VALUES ('"+name+"', '"+us+"', '"+pas+"','"+des+"', '"+dept+"', '"+age+"','"+height+"', '"+weight+"', '"+blood+"')";

                s1.executeUpdate(q3);
                
                   JOptionPane.showMessageDialog(this,"Successfully inserted data");
                   
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField6.setText("");
                    jTextField7.setText("");
                    jTextField8.setText("");
                    jTextField9.setText("");
                    //jComboBox5.setText("");
                    jTextField12.setText("");
                    jTextField14.setText("");
                    jTextField15.setText("");
                    
                    
                    jLabel7.setVisible(false);
                    jLabel8.setVisible(false);
                    jLabel9.setVisible(false);
                    jLabel10.setVisible(false);
                    jLabel11.setVisible(false);
                    jLabel12.setVisible(false);
                    jLabel13.setVisible(false);
                    jLabel14.setVisible(false);
                    jLabel15.setVisible(false);
                    jLabel16.setVisible(false);
                    jLabel17.setVisible(false);
                    jLabel18.setVisible(false);
                    jLabel19.setVisible(false);

                    jTextField2.setVisible(false);
                    jTextField3.setVisible(false);
                    jTextField4.setVisible(false);
                    jComboBox2.setVisible(false);
                    jTextField6.setVisible(false);
                    jTextField7.setVisible(false);
                    jTextField8.setVisible(false);
                    jTextField9.setVisible(false);
                    jComboBox5.setVisible(false);
                    jComboBox3.setVisible(false);
                    jTextField12.setVisible(false);
                    jComboBox4.setVisible(false);
                    jTextField14.setVisible(false);
                    jTextField15.setVisible(false);
                    
                    jButton3.setVisible(false);
           
            }
            if(jComboBox1.getSelectedIndex()==3)
            {

                String q2 = "SELECT * FROM bsmrstu_community.nurse;";
                ResultSet r2= s1.executeQuery(q2);
         
                    String us = jTextField1.getText();
                    String name = jTextField3.getText();
                    String pas = jTextField4.getText();
//                    String gen;
//                    if(jComboBox2.getSelectedIndex() == 0)
//                    {
//                         gen = "Male";
//                    }
//                    else if(jComboBox2.getSelectedIndex() == 1)
//                    {
//                         gen = "Female";
//                    }
//                    else
//                    {
//                         gen = "Others";
//                    }
                    
                    /*
                     String dept = jTextField6.getText();
                    int age = Integer.parseInt(jTextField7.getText());
                    int height = Integer.parseInt(jTextField8.getText());
                    int weight = Integer.parseInt(jTextField9.getText());
                    String donor = jComboBox5.getText();
                    String blood;
                    if(jComboBox3.getSelectedIndex() == 0)
                    {
                         blood = "A+";
                    }
                    else if(jComboBox3.getSelectedIndex() == 1)
                    {
                         blood = "A-";
                    }
                    else if(jComboBox3.getSelectedIndex() == 2)
                    {
                         blood = "B+";
                    }
                    else if(jComboBox3.getSelectedIndex() == 3)
                    {
                         blood = "B-";
                    }
                    else if(jComboBox3.getSelectedIndex() == 4)
                    {
                         blood = "AB+";
                    }
                    else if(jComboBox3.getSelectedIndex() == 5)
                    {
                         blood = "AB-";
                    }
                    else if(jComboBox3.getSelectedIndex() == 7)
                    {
                         blood = "O+";
                    }
                    else 
                    {
                         blood = "O-";
                    }
                    //String sid = jTextField12.getText();
                    String des;
                    if(jComboBox4.getSelectedIndex() == 0)
                    {
                         des = "Lecturer";
                    }
                    else if(jComboBox4.getSelectedIndex() == 1)
                    {
                         des = "Assistant Professor";
                    }
                    else if(jComboBox4.getSelectedIndex() == 2)
                    {
                         des = "Associate Professor";
                    }
                    else
                    {
                         des = "Professor";
                    }
                    
                    String con = jTextField14.getText();
                    String dis = jTextField15.getText();
                    */
                    
                    
                    
                    //JOptionPane.showMessageDialog(this, us + " " +name + " " + pas);

                String q3 = "INSERT INTO `bsmrstu_community`.`nurse` (`name`, `username`, `password`) VALUES ('"+name+"', '"+us+"', '"+pas+"')";
               //                String q3 = "INSERT INTO `bsmrstu_community`.`admin` (`name`, `username`, `password`,`designation`, `department`, `age`,`height`, `weight`, `blood`,`donar`, `district`, `gender`, `contact`) VALUES ('"+name+"', '"+us+"', '"+pas+"','"+des+"', '"+dept+"', '"+age+"','"+height+"', '"+weight+"', '"+blood+"')";

                s1.executeUpdate(q3);
                
                   JOptionPane.showMessageDialog(this,"Successfully inserted data");
                   
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField6.setText("");
                    jTextField7.setText("");
                    jTextField8.setText("");
                    jTextField9.setText("");
                    //.setText("");
                    jTextField12.setText("");
                    jTextField14.setText("");
                    jTextField15.setText("");
                    
                    
                    jLabel7.setVisible(false);
                    jLabel8.setVisible(false);
                    jLabel9.setVisible(false);
                    jLabel10.setVisible(false);
                    jLabel11.setVisible(false);
                    jLabel12.setVisible(false);
                    jLabel13.setVisible(false);
                    jLabel14.setVisible(false);
                    jLabel15.setVisible(false);
                    jLabel16.setVisible(false);
                    jLabel17.setVisible(false);
                    jLabel18.setVisible(false);
                    jLabel19.setVisible(false);

                    jTextField2.setVisible(false);
                    jTextField3.setVisible(false);
                    jTextField4.setVisible(false);
                    jComboBox2.setVisible(false);
                    jTextField6.setVisible(false);
                    jTextField7.setVisible(false);
                    jTextField8.setVisible(false);
                    jTextField9.setVisible(false);
                    jComboBox5.setVisible(false);
                    jComboBox3.setVisible(false);
                    jTextField12.setVisible(false);
                    jComboBox4.setVisible(false);
                    jTextField14.setVisible(false);
                    jTextField15.setVisible(false);
                    
                    jButton3.setVisible(false);
           
            }
            if(jComboBox1.getSelectedIndex()==4)
            {

                String q2 = "SELECT * FROM bsmrstu_community.student;";
                ResultSet r2= s1.executeQuery(q2);
         
                    String us = jTextField1.getText();
                    String name = jTextField3.getText();
                    String pas = jTextField4.getText();
                    String gen;
                    if(jComboBox2.getSelectedIndex() == 0)
                    {
                         gen = "Male";
                    }
                    else if(jComboBox2.getSelectedIndex() == 1)
                    {
                         gen = "Female";
                    }
                    else
                    {
                         gen = "Others";
                    }
                     String dept = jTextField6.getText();
                    int age = Integer.parseInt(jTextField7.getText());
                    int height = Integer.parseInt(jTextField8.getText());
                    int weight = Integer.parseInt(jTextField9.getText());
                    
                    
                    String donor;
                    
                    if(jComboBox5.getSelectedIndex() == 0)
                    {
                         donor = "YES";
                    }
                    else 
                    {
                         donor = "NO";
                    }
                    
                    String blood;
                    if(jComboBox3.getSelectedIndex() == 0)
                    {
                         blood = "A+";
                    }
                    else if(jComboBox3.getSelectedIndex() == 1)
                    {
                         blood = "A-";
                    }
                    else if(jComboBox3.getSelectedIndex() == 2)
                    {
                         blood = "B+";
                    }
                    else if(jComboBox3.getSelectedIndex() == 3)
                    {
                         blood = "B-";
                    }
                    else if(jComboBox3.getSelectedIndex() == 4)
                    {
                         blood = "AB+";
                    }
                    else if(jComboBox3.getSelectedIndex() == 5)
                    {
                         blood = "AB-";
                    }
                    else if(jComboBox3.getSelectedIndex() == 7)
                    {
                         blood = "O+";
                    }
                    else 
                    {
                         blood = "O-";
                    }
                    //String sid = jTextField12.getText();
//                    String des;
//                    if(jComboBox4.getSelectedIndex() == 0)
//                    {
//                         des = "Lecturer";
//                    }
//                    else if(jComboBox4.getSelectedIndex() == 1)
//                    {
//                         des = "Assistant Professor";
//                    }
//                    else if(jComboBox4.getSelectedIndex() == 2)
//                    {
//                         des = "Associate Professor";
//                    }
//                    else
//                    {
//                         des = "Professor";
//                    }
                    
                    String con = jTextField14.getText();
                    String dis = jTextField15.getText();
                    String sid = jTextField12.getText();
                    
                    
                    
                    //JOptionPane.showMessageDialog(this, us + " " +name + " " + pas);

                String q3 = "INSERT INTO `bsmrstu_community`.`student` (`id`,`name`, `username`, `password`, `department`, `age`,`height`, `weight`, `blood`,`donar`, `district`, `gender`, `contact`) VALUES ('"+sid+"','"+name+"', '"+us+"', '"+pas+"', '"+dept+"', '"+age+"','"+height+"', '"+weight+"','"+blood+"', '"+donor+"', '"+dis+"','"+gen+"', '"+con+"')";
               //                String q3 = "INSERT INTO `bsmrstu_community`.`admin` (`name`, `username`, `password`,`designation`, `department`, `age`,`height`, `weight`, `blood`,`donar`, `district`, `gender`, `contact`) VALUES ('"+name+"', '"+us+"', '"+pas+"','"+des+"', '"+dept+"', '"+age+"','"+height+"', '"+weight+"', '"+blood+"')";

                s1.executeUpdate(q3);
                
                   JOptionPane.showMessageDialog(this,"Successfully inserted data");
                   
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField6.setText("");
                    jTextField7.setText("");
                    jTextField8.setText("");
                    jTextField9.setText("");
                    //jComboBox5.setText("");
                    jTextField12.setText("");
                    jTextField14.setText("");
                    jTextField15.setText("");
                    
                    
                    jLabel7.setVisible(false);
                    jLabel8.setVisible(false);
                    jLabel9.setVisible(false);
                    jLabel10.setVisible(false);
                    jLabel11.setVisible(false);
                    jLabel12.setVisible(false);
                    jLabel13.setVisible(false);
                    jLabel14.setVisible(false);
                    jLabel15.setVisible(false);
                    jLabel16.setVisible(false);
                    jLabel17.setVisible(false);
                    jLabel18.setVisible(false);
                    jLabel19.setVisible(false);

                    jTextField2.setVisible(false);
                    jTextField3.setVisible(false);
                    jTextField4.setVisible(false);
                    jComboBox2.setVisible(false);
                    jTextField6.setVisible(false);
                    jTextField7.setVisible(false);
                    jTextField8.setVisible(false);
                    jTextField9.setVisible(false);
                    jComboBox5.setVisible(false);
                    jComboBox3.setVisible(false);
                    jTextField12.setVisible(false);
                    jComboBox4.setVisible(false);
                    jTextField14.setVisible(false);
                    jTextField15.setVisible(false);
                    
                    jButton3.setVisible(false);
           
            }
            
            
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Insert with right format");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
