
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.codejava.e_health.E_health;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("User Type");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Teacher", "Doctor", "Nurse", "Student" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 250, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, -1, -1));

        txtuser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, 250, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login.png"))); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 500, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 500, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("Login");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 51, 255), null, null));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, -1, -1));

        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 330, -1, -1));

        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 330, -1, -1));

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 250, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginfinal.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new login().setVisible(false);
        new welcome().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {//student ss = new student();
            
        //declare the parameter of connection
        String url = "jdbc:mysql://localhost:3307/bsmrstu_community";
        String user = "root";
        String password = "juwelmallick";
        Class.forName("com.mysql.cj.jdbc.Driver");
         
        //for a new connection with database
        Connection c  = DriverManager.getConnection(url,user, password);
        //Statement statement = c.createStatement();
        //String query1 = "SELECT * FROM bsmrstu_community.password";//WHERE username=? and password=? and usertype=?;
        Statement s1 = c.createStatement();
       
        
        if(jComboBox1.getSelectedIndex()==0)
             {
                String q1 = "SELECT * FROM bsmrstu_community.admin";
                ResultSet r1= s1.executeQuery(q1);
                
                String u1 = txtuser.getText();
                String p1 = jPasswordField1.getText();
                 int n=0;
             while(r1.next())
             {
                String us, pas;
                us = r1.getString("username");
                pas = r1.getString("password");
                
                if(txtuser.getText().equals(us) && jPasswordField1.getText().equals(pas) )
                {
                    n=1;
                    new admin().setVisible(true);
                    new login().setVisible(false);
                 break;
                } 
             } if(n==0)
                     {
                         JOptionPane.showMessageDialog(this, "Incorrect username or password");
                     }
            }
        
        else if(jComboBox1.getSelectedIndex()==1)
             {
                
                 String q1 = "SELECT * FROM bsmrstu_community.teacher";
                ResultSet r1= s1.executeQuery(q1);
                String u1 = txtuser.getText();
                String p1 = jPasswordField1.getText();
                 int n=0;
             while(r1.next())
             {
                String us, pas;
                us = r1.getString("username");
                pas = r1.getString("password");
                
                if(txtuser.getText().equals(us) && jPasswordField1.getText().equals(pas) )
                {
                    n=1;
                    new teacher(u1).setVisible(true);
                    new login().setVisible(false);
                 break;
                } 
             } if(n==0)
                     {
                         JOptionPane.showMessageDialog(this, "Incorrect username or password");
                     }
            }
        
        else if(jComboBox1.getSelectedIndex()==2)
             {
                
                 String q1 = "SELECT * FROM bsmrstu_community.doctor";
                ResultSet r1= s1.executeQuery(q1);
                String u1 = txtuser.getText();
                String p1 = jPasswordField1.getText();
                 int n=0;
             while(r1.next())
             {
                String us, pas;
                us = r1.getString("username");
                pas = r1.getString("password");
                
                if(txtuser.getText().equals(us) && jPasswordField1.getText().equals(pas) )
                {
                    n=1;
                    new doctor().setVisible(true);
                    new login().setVisible(false);
                 break;
                } 
             } if(n==0)
                     {
                         JOptionPane.showMessageDialog(this, "Incorrect username or password");
                     }
            }
        
        else if(jComboBox1.getSelectedIndex()==3)
             {
                
                 String q1 = "SELECT * FROM bsmrstu_community.nurse";
                ResultSet r1= s1.executeQuery(q1);
                String u1 = txtuser.getText();
                String p1 = jPasswordField1.getText();
                 int n=0;
             while(r1.next())
             {
                String us, pas;
                us = r1.getString("username");
                pas = r1.getString("password");
                
                if(txtuser.getText().equals(us) && jPasswordField1.getText().equals(pas) )
                {
                    n=1;
                    new nurse().setVisible(true);
                    new login().setVisible(false);
                 break;
                } 
             } if(n==0)
                     {
                         JOptionPane.showMessageDialog(this, "Incorrect username or password");
                     }
            }
        else 
             {
                 //student ss = new student();
                 
                //ss.jTextField1.setVisible(true);
                
                 String q1 = "SELECT * FROM bsmrstu_community.student";
                ResultSet r1= s1.executeQuery(q1);
                String u1 = txtuser.getText();
                
                String p1 = jPasswordField1.getText();
                 int n=0;
             while(r1.next())
             {
                String us, pas;
                us = r1.getString("username");
                pas = r1.getString("password");
                
                if(txtuser.getText().equals(us) && jPasswordField1.getText().equals(pas) )
                {//ss.jTextField1.setText(txtuser.getText());
                    n=1;
                    new student(u1).setVisible(true);
                    new login().setVisible(false);
                 break;
                } 
             } if(n==0)
                     {
                         JOptionPane.showMessageDialog(this, "Incorrect username or password");
                     }
            }
        /*
        
        PreparedStatement pst;
        pst = c.prepareStatement(query1);
        pst.setString(1, txtuser.getText());
        pst.setString(2, jPasswordField1.getText());
        pst.setString(3, String.valueOf(jComboBox1.getSelectedItem()));
        ResultSet result= pst.executeQuery(query1);
        
        
        //(start) display the database info(database read)
        Statement statement = c.createStatement();
        String query2 = "SELECT * FROM bsmrstu_community";
        ResultSet result2= statement.executeQuery(query2);
         
         while(result2.next())
         {
            String username1, password1, usertype1;
            username1 = result.getString("username");
            password1 = result.getString("password");
            usertype1 = result.getString("password");
           // System.out.println(username1 + " " + password1+ " "+ usertype1);
             int a;
        a = JOptionPane.showConfirmDialog(null, "username1 + \" \" + password1+ \" \"+ usertype1","Select", JOptionPane.YES_NO_OPTION);
        if(a==0)
            System.exit(0);
         }
         System.out.println("\n");
         */
        //(end) display the database info(database read)
        
        //(start) display the database info(database read)
        
//        
//         
//         if(result.next())
//         {
//             JOptionPane.showMessageDialog(this, " you are login as "+result.getString("usertype"));
//             if(jComboBox1.getSelectedIndex()==0)
//             {
//                 new admin().setVisible(true);
//                 new login().setVisible(false);
//             } 
//             else if(jComboBox1.getSelectedIndex()==1)
//             {
//                 new teacher().setVisible(true);
//                 new login().setVisible(false);
//             } 
//             else if(jComboBox1.getSelectedIndex()==2)
//             {
//                 new doctor().setVisible(true);
//                 new login().setVisible(false);
//             } 
//             
//             
//         }else
//             {
//                 JOptionPane.showMessageDialog(this, "username and password incorrect");
//             }
        }catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(E_health.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
